// file: countryToLanguages.ts

export const countryToLanguages: Record<string, string[]> = {
  "Afghanistan": ["ps-AF"],
  "Albania": ["sq-AL"],
  "Algeria": ["ar-DZ"],
  "Australia": ["en-AU"],
  "Austria": ["de-AT"],
  "Azerbaijan": ["az-AZ"],
  "Bahrain": ["ar-BH"],
  "Bangladesh": ["bn-BD"],
  "Belgium": ["fr-BE", "nl-BE"],
  "Bolivia": ["es-BO"],
  "Bosnia and Herzegovina": ["bs-BA"],
  "Brazil": ["pt-BR"],
  "Bulgaria": ["bg-BG"],
  "Cambodia": ["km-KH"],
  "Canada": ["en-CA", "fr-CA", "iu-CANS-CA", "iu-LATN-CA"],
  "Chile": ["es-CL"],
  "China": ["zh-CN", "wuu-CN", "yue-CN"],
  "Colombia": ["es-CO"],
  "Costa Rica": ["es-CR"],
  "Croatia": ["hr-HR"],
  "Cuba": ["es-CU"],
  "Czech Republic": ["cs-CZ"],
  "Denmark": ["da-DK"],
  "Dominican Republic": ["es-DO"],
  "Ecuador": ["es-EC"],
  "Egypt": ["ar-EG"],
  "El Salvador": ["es-SV"],
  "Ethiopia": ["am-ET"],
  "Finland": ["fi-FI"],
  "France": ["fr-FR"],
  "Georgia": ["ka-GE"],
  "Germany": ["de-DE"],
  "Greece": ["el-GR"],
  "Hong Kong": ["en-HK", "zh-HK"],
  "Hungary": ["hu-HU"],
  "Iceland": ["is-IS"],
  "India": ["en-IN", "gu-IN", "hi-IN", "kn-IN", "ml-IN", "mr-IN", "or-IN", "pa-IN", "ta-IN", "te-IN", "ur-IN"],
  "Indonesia": ["id-ID", "jv-ID", "su-ID"],
  "Iran": ["fa-IR"],
  "Iraq": ["ar-IQ"],
  "Ireland": ["en-IE", "ga-IE"],
  "Israel": ["he-IL"],
  "Italy": ["it-IT"],
  "Japan": ["ja-JP"],
  "Jordan": ["ar-JO"],
  "Kazakhstan": ["kk-KZ"],
  "Kenya": ["en-KE", "sw-KE"],
  "Kuwait": ["ar-KW"],
  "Laos": ["lo-LA"],
  "Latvia": ["lv-LV"],
  "Lebanon": ["ar-LB"],
  "Libya": ["ar-LY"],
  "Lithuania": ["lt-LT"],
  "Malaysia": ["ms-MY", "ta-MY"],
  "Malta": ["mt-MT"],
  "Mexico": ["es-MX"],
  "Mongolia": ["mn-MN"],
  "Morocco": ["ar-MA"],
  "Myanmar": ["my-MM"],
  "Nepal": ["ne-NP"],
  "Netherlands": ["nl-NL"],
  "New Zealand": ["en-NZ"],
  "Nicaragua": ["es-NI"],
  "Nigeria": ["en-NG"],
  "North Macedonia": ["mk-MK"],
  "Norway": ["nb-NO"],
  "Oman": ["ar-OM"],
  "Pakistan": ["ur-PK"],
  "Panama": ["es-PA"],
  "Paraguay": ["es-PY"],
  "Peru": ["es-PE"],
  "Philippines": ["en-PH", "fil-PH"],
  "Poland": ["pl-PL"],
  "Portugal": ["pt-PT"],
  "Puerto Rico": ["es-PR"],
  "Qatar": ["ar-QA"],
  "Romania": ["ro-RO"],
  "Russia": ["ru-RU"],
  "Saudi Arabia": ["ar-SA"],
  "Serbia": ["sr-RS", "sr-LATN-RS"],
  "Singapore": ["en-SG", "ta-SG"],
  "Slovakia": ["sk-SK"],
  "Slovenia": ["sl-SI"],
  "Somalia": ["so-SO"],
  "South Africa": ["af-ZA", "en-ZA", "zu-ZA"],
  "South Korea": ["ko-KR"],
  "Spain": ["es-ES", "ca-ES", "eu-ES", "gl-ES"],
  "Sri Lanka": ["si-LK", "ta-LK"],
  "Sweden": ["sv-SE"],
  "Switzerland": ["de-CH", "fr-CH"],
  "Syria": ["ar-SY"],
  "Taiwan": ["zh-TW"],
  "Tanzania": ["en-TZ", "sw-TZ"],
  "Thailand": ["th-TH"],
  "Tunisia": ["ar-TN"],
  "Turkey": ["tr-TR"],
  "Ukraine": ["uk-UA"],
  "United Arab Emirates": ["ar-AE"],
  "United Kingdom": ["cy-GB", "en-GB"],
  "United States": ["en-US", "es-US"],
  "Uruguay": ["es-UY"],
  "Uzbekistan": ["uz-UZ"],
  "Venezuela": ["es-VE"],
  "Vietnam": ["vi-VN"],
  "Yemen": ["ar-YE"]
}; 